### ISSUE TITLE
Netlify deploy fails

### ISSUE THREAD

**Issue by heymattcastillo** [jgarber623/jekyll-netlify-headers#19]
I'm running into an issue and can't seem to find how to fix it. Anytime I try to deploy to Netlify using your plugin, it fails because jekyll-netlify-headers is incompatible with my ruby version.

`3:25:46 PM: jekyll-netlify-headers-0.1.3 requires ruby version >= 2.4, which is incompatible
3:25:46 PM: with the current version, ruby 2.3.6p384`

Any guidance on how to make sure these are compatible with each other?

**Comment by heymattcastillo** [comment]
Cancel that — I added a .ruby-version file and it works now.

**Comment by jgarber623** [comment]
@interactivematt Glad you got things working and thanks for using the gem!
